package com.ccos.retro.event

import com.ccos.retro.data.LaunchSnapshot

/**
 * Aft-view engine cluster. One enum, used by wallpaper AND MCC.
 * merlin27 is three octawebs. Never a concentric 27-ring.
 * Unknown: do not invent a ring.
 */
enum class EnginePattern {
    MERLIN9,
    MERLIN27,
    MERLIN_VAC,
    RAPTOR33,
    RAPTOR6,
    RS25_4,
    RL10,
    BE4_7,
    BE4_2,
    KOROLEV,
    KOROLEV_UPPER,
    ELECTRON9,
    ARIANE,
    LM5,
    LE9_2,
    GLENN7,
    CHAMBER4,
    H3_2,
    VACUUM1,
    SOLIDS,
    REAVER4,
    PROTON6,
    RD180_2,
    VIKAS2,
    UNKNOWN
}

/**
 * Data-driven vehicle book. Add a [VehicleSpec] when a new rocket shows up.
 * Drawing still keys off [VehicleSpec.family]. Change numbers here, not in the views.
 * Starship 14 is a new row (or the same row until the hardware actually changes).
 */
data class VehicleSpec(
    val id: String,
    val family: String,
    val tokens: List<String>,
    val s1Engines: Int,
    val s2Engines: Int,
    val recoverable: Boolean,
    val methalox: Boolean,
    val fuelName: String,
    val oxName: String = "LOX",
    val boostbackLit: Int,
    val landingLit: Int,
    val boostbackSec: Float = 32f,
    val landingBurnSec: Float = 22f,
    val residual: Float = 0.08f,
    val engineName: String,
    val s1Thrust: String,
    val s2Thrust: String,
    val ispVac: String,
    val mixRatio: String,
    val chamberBar: String,
    val s1Dry: String,
    val s1Prop: String,
    val nerdNote: String,
    /** False: do not invent a drawing or numbers. Show UPDATE REQUIRED. */
    val verified: Boolean = true,
    /** Silhouette key. Zhuque-3 is Falcon-shaped, not Long March. */
    val drawFamily: String = family,
    val s1Pattern: EnginePattern = EnginePattern.UNKNOWN,
    val s2Pattern: EnginePattern = EnginePattern.UNKNOWN,
    val s2Dry: String = "—",
    val s2Prop: String = "—",
    val s1Isp: String = "—",
    val s2Isp: String = "",
    val s1Name: String = "",
    val s2Name: String = "",
    val s2EngineName: String = ""
) {
    fun pattern(stage: Int): EnginePattern = if (stage >= 2) s2Pattern else s1Pattern
    fun stageName(stage: Int, fallback: String): String {
        val named = if (stage >= 2) s2Name else s1Name
        return named.ifBlank { fallback }
    }
    fun dry(stage: Int): String = if (stage >= 2) s2Dry else s1Dry
    fun prop(stage: Int): String = if (stage >= 2) s2Prop else s1Prop
    fun isp(stage: Int): String {
        val own = if (stage >= 2) s2Isp else s1Isp
        return own.ifBlank { ispVac }
    }
    fun engineLabel(stage: Int): String =
        if (stage >= 2) s2EngineName.ifBlank { engineName } else engineName
}

object VehicleCatalog {

    private val GENERIC = VehicleSpec(
        id = "generic",
        family = "generic",
        tokens = emptyList(),
        s1Engines = 9,
        s2Engines = 1,
        recoverable = false,
        methalox = false,
        fuelName = "RP-1",
        boostbackLit = 0,
        landingLit = 0,
        engineName = "UNKNOWN",
        s1Thrust = "—",
        s2Thrust = "—",
        ispVac = "—",
        mixRatio = "—",
        chamberBar = "—",
        s1Dry = "—",
        s1Prop = "—",
        nerdNote = "Not in the vehicle book. Drawing and numbers ship in a later update. We will not invent them.",
        verified = false,
        drawFamily = "generic",
        s1Pattern = EnginePattern.UNKNOWN,
        s2Pattern = EnginePattern.UNKNOWN
    )

    /**
     * First match wins. Put more specific tokens (Falcon Heavy, Long March 5) first.
     */
    val all: List<VehicleSpec> = listOf(
        VehicleSpec(
            id = "starship",
            family = "starship",
            tokens = listOf("starship", "super heavy"),
            s1Engines = 33,
            s2Engines = 6,
            recoverable = true,
            methalox = true,
            fuelName = "CH4",
            boostbackLit = 13,
            landingLit = 13,
            boostbackSec = 32f,
            landingBurnSec = 22f,
            engineName = "RAPTOR SL",
            s1Thrust = "74 MN SL",
            s2Thrust = "15 MN VAC",
            ispVac = "~350–380 s VAC",
            mixRatio = "3.6 O/F EST",
            chamberBar = "300 BAR EST",
            s1Dry = "~275 t EST",
            s1Prop = "~3400 t",
            nerdNote = "Full-flow staged combustion. Best part is no part. Update this row when Raptor changes.",
            s1Pattern = EnginePattern.RAPTOR33,
            s2Pattern = EnginePattern.RAPTOR6,
            s2Dry = "~85–126 t EST",
            s2Prop = "~1200–1500 t EST",
            s1Isp = "~327 s SL EST",
            s2Isp = "~350–380 s VAC",
            s1Name = "SUPER HEAVY",
            s2Name = "STARSHIP",
            s2EngineName = "RAPTOR 3 SL + 3 VAC"
        ),
        VehicleSpec(
            id = "fh",
            family = "fh",
            tokens = listOf("falcon heavy"),
            s1Engines = 27,
            s2Engines = 1,
            recoverable = true,
            methalox = false,
            fuelName = "RP-1",
            oxName = "LOX",
            boostbackLit = 3,
            landingLit = 3,
            engineName = "MERLIN 1D",
            s1Thrust = "22.8 MN SL",
            s2Thrust = "934 kN VAC",
            ispVac = "348 s",
            mixRatio = "2.36 O/F",
            chamberBar = "97 BAR",
            s1Dry = "3x ~26 t",
            s1Prop = "3x ~400 t",
            nerdNote = "Falcon Heavy: 3-core kerolox (LOX cyan + RP amber). Stamp 125 Soft-PASS vehicle_fh_* fills via drawArtThenCoreTanks(fh, cores=3). No propane pills.",
            verified = true,
            drawFamily = "fh",
            s1Pattern = EnginePattern.MERLIN27,
            s2Pattern = EnginePattern.MERLIN_VAC
        ),
        VehicleSpec(
            id = "f9",
            family = "f9",
            tokens = listOf("falcon 9", "falcon-9", "falcon9", "f9 block", "falcon"),
            s1Engines = 9,
            s2Engines = 1,
            recoverable = true,
            methalox = false,
            fuelName = "RP-1",
            boostbackLit = 3,
            landingLit = 3,
            engineName = "MERLIN 1D",
            s1Thrust = "7.6 MN SL",
            s2Thrust = "934 kN VAC",
            ispVac = "348 s",
            mixRatio = "2.36 O/F",
            chamberBar = "97 BAR",
            s1Dry = "~26 t",
            s1Prop = "~400 t",
            nerdNote = "Octaweb. Center engine for landing. The workhorse that paid for the steel one.",
            s1Pattern = EnginePattern.MERLIN9,
            s2Pattern = EnginePattern.MERLIN_VAC
        ),
        VehicleSpec(
            id = "glenn",
            family = "glenn",
            tokens = listOf("new glenn"),
            s1Engines = 7,
            s2Engines = 2,
            recoverable = true,
            methalox = true,
            fuelName = "CH4",
            boostbackLit = 7,
            landingLit = 7,
            engineName = "BE-4 / BE-3U",
            s1Thrust = "17 MN SL",
            s2Thrust = "1.6 MN VAC",
            ispVac = "445 s",
            mixRatio = "3.5 O/F",
            chamberBar = "134 BAR",
            s1Dry = "~70 t",
            s1Prop = "~1000 t",
            nerdNote = "Oxygen-rich staged combustion. The hat has a kick stage. Do not sit on it.",
            s1Pattern = EnginePattern.BE4_7,
            s2Pattern = EnginePattern.BE4_2
        ),
        VehicleSpec(
            id = "vulcan",
            family = "vulcan",
            tokens = listOf("vulcan centaur", "vulcan"),
            s1Engines = 2,
            s2Engines = 2,
            recoverable = false,
            methalox = true,
            fuelName = "CH4",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "BE-4 / RL10",
            s1Thrust = "4.9 MN SL",
            s2Thrust = "200 kN VAC",
            ispVac = "460 s",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "Two BE-4. Centaur V. Solids are solids: no liquid bells on the ENG plate.",
            verified = true,
            drawFamily = "vulcan",
            s1Pattern = EnginePattern.BE4_2,
            s2Pattern = EnginePattern.RL10
        ),
        VehicleSpec(
            id = "sls",
            family = "sls",
            tokens = listOf("sls", "space launch system", "artemis"),
            s1Engines = 4,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "LH2",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "RS-25 / RL10",
            s1Thrust = "7.4 MN + SRB",
            s2Thrust = "110 kN VAC",
            ispVac = "452 s",
            mixRatio = "6.0 O/F",
            chamberBar = "206 BAR",
            s1Dry = "~85 t core",
            s1Prop = "~980 t",
            nerdNote = "Shuttle leftovers at a Saturn price. The solids do the talking.",
            s1Pattern = EnginePattern.RS25_4,
            s2Pattern = EnginePattern.RL10
        ),
        VehicleSpec(
            id = "soyuz",
            family = "soyuz",
            tokens = listOf("soyuz"),
            s1Engines = 20,
            s2Engines = 4,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "RD-107 / RD-0110",
            s1Thrust = "4.1 MN SL",
            s2Thrust = "298 kN VAC",
            ispVac = "326 s",
            mixRatio = "2.6 O/F",
            chamberBar = "60 BAR",
            s1Dry = "~30 t",
            s1Prop = "~120 t",
            nerdNote = "Korolev cross. Four boosters, one core. If it looks 1960s, that is because it works.",
            s1Pattern = EnginePattern.KOROLEV,
            s2Pattern = EnginePattern.KOROLEV_UPPER
        ),
        VehicleSpec(
            id = "electron",
            family = "electron",
            tokens = listOf("electron", "rocket lab"),
            s1Engines = 9,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "RUTHERFORD",
            s1Thrust = "224 kN SL",
            s2Thrust = "26 kN VAC",
            ispVac = "343 s",
            mixRatio = "2.4 O/F",
            chamberBar = "—",
            s1Dry = "~1.2 t",
            s1Prop = "~9 t",
            nerdNote = "Electric pumps. Stamp 120: polished vehicle_electron_* fills (MD5 D8AB6A stack). Continuous paper-doll.",
            drawFamily = "electron",
            verified = true,
            s1Pattern = EnginePattern.ELECTRON9,
            s2Pattern = EnginePattern.MERLIN_VAC
        ),
        VehicleSpec(
            id = "ariane",
            family = "ariane",
            tokens = listOf("ariane"),
            s1Engines = 1,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "LH2",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "VULCAIN / VINCI",
            s1Thrust = "1.4 MN + SRB",
            s2Thrust = "180 kN VAC",
            ispVac = "457 s",
            mixRatio = "6.0 O/F",
            chamberBar = "118 BAR",
            s1Dry = "~55 t",
            s1Prop = "~180 t",
            nerdNote = "Kourou. Solids have no liquid bells on the ENG plate. One Vulcain.",
            s1Pattern = EnginePattern.ARIANE,
            s2Pattern = EnginePattern.RL10
        ),
        VehicleSpec(
            id = "lm5",
            family = "lm5",
            tokens = listOf("long march 5", "cz-5", "cz5"),
            s1Engines = 10,
            s2Engines = 2,
            recoverable = false,
            methalox = false,
            fuelName = "LH2",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-77 / YF-75D",
            s1Thrust = "10.6 MN SL",
            s2Thrust = "176 kN VAC",
            ispVac = "442 s",
            mixRatio = "6.0 O/F",
            chamberBar = "—",
            s1Dry = "~18 t core",
            s1Prop = "~170 t",
            nerdNote = "China's heavy. Four boosters, hydrolox core. The weather sat has a good memory.",
            s1Pattern = EnginePattern.LM5,
            s2Pattern = EnginePattern.BE4_2
        ),

        VehicleSpec(
            id = "cz2d",
            family = "cz2d",
            tokens = listOf("long march 2d", "cz-2d", "cz2d", "2d/yz-3", "yz-3", "yz3"),
            s1Engines = 4,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "UDMH",
            oxName = "N2O4",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-21C",
            s1Thrust = "2961.6 kN SL",
            s2Thrust = "742 kN VAC",
            ispVac = "~300 s",
            mixRatio = "N2O4/UDMH",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "CZ-2D: 4×YF-20-family as YF-21C first stage; second stage YF-24C (YF-22C + verniers). Optional YZ-3 upper (YF-50D ~6.5 kN) when stacked. Hypergolic; not recoverable. Published Wikipedia/Orbit Codex — no invent.",
            verified = true,
            drawFamily = "cz2d",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "1st (YF-21C)",
            s2Name = "2nd (YF-24C)",
            s2EngineName = "YF-24C"
        ),
        VehicleSpec(
            id = "cz8a",
            family = "cz8a",
            tokens = listOf(
                "long march 8a",
                "cz-8a",
                "cz8a",
                "长征八号甲"
            ),
            s1Engines = 4,
            s2Engines = 2,
            recoverable = false,
            methalox = false,
            fuelName = "LH2",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-100 / YF-75H",
            s1Thrust = "~4800 kN SL class",
            s2Thrust = "2x YF-75H/DA VAC",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~371 t GLOW class",
            nerdNote = "CZ-8A / Long March 8A (CALT/CASC): ~50.5 m, 3.35 m core, ~371 t liftoff, ~480 t-class / ~4800 kN liftoff thrust class. Stack 2 + 2 strap-ons: core S1 2x YF-100 kerolox, each booster 1x YF-100; S2 2x YF-75H/YF-75DA hydrolox (3.35 m); fairing up to ~5.2 m published. ~7 t to 700 km SSO. Maiden 2025-02-11 Wenchang. Published CALT/state media/skyrocket/Wikipedia-class — no invent. Da Vinci art: vehicle_cz8a_*. Stamp 118: S2 hydrolox YF-75H/DA (fuelName LH2); S1+SRB still YF-100 kerolox. Art vehicle_cz8a_* continuous stack.",
            verified = true,
            drawFamily = "cz8a",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.BE4_2,
            s1Name = "1st+boosters (YF-100)",
            s2Name = "2nd (YF-75H/DA)",
            s2EngineName = "YF-75H/DA"
        ),

        VehicleSpec(
            id = "cz6a",
            family = "cz6a",
            tokens = listOf(
                "long march 6a",
                "cz-6a",
                "cz6a",
                "chang zheng 6a",
                "长征六号甲"
            ),
            s1Engines = 2, // liquid core (YF-100×2); 4×FG-112 SRBs in nerdNote
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "RP",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-100 / YF-115 + FG-112 solid",
            s1Thrust = "~7230 kN SL class (core+SRB)",
            s2Thrust = "1x YF-115 VAC",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~530 t GLOW class",
            nerdNote = "CZ-6A / Long March 6A (SAST/CASC): ~50 m, 3.35 m core, ~530 t liftoff, ~7230 kN liftoff thrust class. Stack 2 + 4 solid strap-ons (FG-112 Ø2.0×15.1 m HTPB solid). Core S1 2x YF-100 kerolox; S2 1x YF-115 kerolox (NOT hydrolox). Fairing ~4.2 m Ø / ~5.7 m class (5.2 m option published). ~5 t to 700 km SSO class. Maiden 2022-03-29 Taiyuan LC-9A. Published Wikipedia/NSF/CASC-class — no invent. Da Vinci art: vehicle_cz6a_* GOLD 2026-09-23 (SS×6 orange LM hull, solid SRBs, kerolox fills both stages).",
            verified = true,
            drawFamily = "cz6a",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "1st+4×SRB (YF-100+FG-112)",
            s2Name = "2nd (YF-115)",
            s2EngineName = "YF-115"
        ),


        VehicleSpec(
            id = "kz11",
            family = "kz11",
            tokens = listOf(
                "kuaizhou 11",
                "kuaizhou-11",
                "kz-11",
                "kz11",
                "kz 11",
                "expace kz-11",
                "快舟十一号"
            ),
            s1Engines = 1,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "HTPB/APCP",
            oxName = "solid",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "solid",
            s1Thrust = "S1 solid",
            s2Thrust = "S2-S4 solid",
            ispVac = "-",
            mixRatio = "solid grain",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Kuaizhou-11 (ExPace): ALL-SOLID 4-stage paper-doll. Art vehicle_kz11_*. Grain=fuel ochre; ox empty. No propane pills.",
            verified = true,
            drawFamily = "kz11",
            s1Pattern = EnginePattern.VACUUM1,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "1st (solid)",
            s2Name = "upper (S2-S4)",
            s2EngineName = "solid"
        ),

        VehicleSpec(
            id = "cz12",
            family = "cz12",
            tokens = listOf(
                "long march 12a",
                "cz-12a",
                "cz12a",
                "lm-12a",
                "lm12a",
                "12a",
                "long march 12",
                "cz-12",
                "cz12",
                "lm-12",
                "lm12",
                "长征十二号"
            ),
            s1Engines = 4,
            s2Engines = 2,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-100K",
            s1Thrust = "4x YF-100K SL",
            s2Thrust = "2x YF-115 VAC",
            ispVac = "-",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "CZ-12 / Long March 12 (CALT/CASC): kerolox paper-doll pack. S1 4x YF-100K + S2 2x YF-115 (published class). Art: vehicle_cz12_* (stack/s1/s2/fairing + tank ox/fuel + flames). No propane pills. Unpublished fields left Unknown.",
            verified = true,
            drawFamily = "cz12",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.BE4_2,
            s1Name = "1st (YF-100K)",
            s2Name = "2nd (YF-115)",
            s2EngineName = "YF-115"
        ),

        VehicleSpec(
            id = "lm",
            family = "lm",
            tokens = listOf("long march", "cz-"),
            s1Engines = 4,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "UDMH",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "YF-100 / YF-20",
            s1Thrust = "—",
            s2Thrust = "—",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "Long March catch-all. Specific CZ variants get their own row. We will not invent a drawing.",
            verified = false,
            drawFamily = "generic",
            s1Pattern = EnginePattern.UNKNOWN,
            s2Pattern = EnginePattern.UNKNOWN
        ),

        VehicleSpec(
            id = "lvm3",
            family = "lvm3",
            tokens = listOf("lvm3", "lvm-3", "gslv mk iii", "gslv mk-iii", "gslv-mk3", "gslv mk3"),
            s1Engines = 2,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "UH25",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "VIKAS / CE-20",
            s1Thrust = "1.6 MN + S200",
            s2Thrust = "186 kN VAC",
            ispVac = "443 s",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "LVM3. Two S200 solids, L110 with 2 Vikas, C25 with CE-20. Solids are not liquid bells.",
            verified = true,
            drawFamily = "lvm3",
            s1Pattern = EnginePattern.VIKAS2,
            s2Pattern = EnginePattern.VACUUM1
        ),
        VehicleSpec(
            id = "pslv",
            family = "isro",
            tokens = listOf("pslv"),
            s1Engines = 0,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "HTPB",
            oxName = "—",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "S139 / VIKAS",
            s1Thrust = "4.85 MN S139",
            s2Thrust = "803.7 kN VAC",
            ispVac = "293 s",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~138 t",
            nerdNote = "PSLV. S139 HTPB core ~4847 kN SL. PS2: 1×Vikas-2B N2O4/UDMH ~804 kN vac. Strap-ons vary CA/XL/DL/QL. Solids are not liquid bells.",
            verified = true,
            drawFamily = "isro",
            s1Pattern = EnginePattern.SOLIDS,
            s2Pattern = EnginePattern.VACUUM1,
            s2Prop = "~42 t",
            s1Isp = "237 s SL",
            s2Isp = "293 s VAC",
            s2EngineName = "VIKAS-2B"
        ),

        VehicleSpec(
            id = "gslv",
            family = "isro",
            tokens = listOf("gslv mk ii", "gslv mk-ii", "gslv mk2", "gslv-mk2", "gslv"),
            s1Engines = 4,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "UDMH",
            oxName = "N2O4",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "VIKAS L40H / CE-7.5",
            s1Thrust = "3.04 MN L40H + S139",
            s2Thrust = "75 kN VAC",
            ispVac = "454 s",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "GSLV Mk II. S139 HTPB ~4847 kN + 4×L40H Vikas ~760 kN each. GS2 Vikas-2B ~847 kN. CUS CE-7.5 LOX/LH2 75 kN. Solids are not liquid bells.",
            verified = true,
            drawFamily = "isro",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.VACUUM1,
            s2Prop = "~12.8–15 t",
            s1Isp = "262 s SL",
            s2Isp = "454 s VAC",
            s1Name = "GS1 + L40H",
            s2Name = "CUS",
            s2EngineName = "CE-7.5"
        ),
        VehicleSpec(
            id = "isro",
            family = "isro",
            tokens = listOf("pslv", "gslv"),
            s1Engines = 0,
            s2Engines = 0,
            recoverable = false,
            methalox = false,
            fuelName = "HTPB",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "UNKNOWN",
            s1Thrust = "—",
            s2Thrust = "—",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "PSLV and GSLV Mk II are not one vehicle. Add a row per stack. We will not invent a drawing.",
            verified = false,
            drawFamily = "generic",
            s1Pattern = EnginePattern.UNKNOWN,
            s2Pattern = EnginePattern.UNKNOWN
        ),
        VehicleSpec(
            id = "zq3",
            family = "zq",
            tokens = listOf("zhuque-3", "zhuque 3", "zq-3", "zq3"),
            s1Engines = 9,
            s2Engines = 1,
            recoverable = true,
            methalox = true,
            fuelName = "CH4",
            boostbackLit = 3,
            landingLit = 1,
            engineName = "TQ-12A / TQ-15A",
            s1Thrust = "7.2 MN SL",
            s2Thrust = "944 kN VAC",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~550 t GROSS",
            nerdNote = "Stainless methalox. 9×TQ-12A + 1×TQ-15A. Grid fins and legs. Stamp 118: paper-doll vehicle_zq3_* (not F9 art). Stainless methalox. Y2 recovered Minqin ~T+8.",
            verified = true,
            drawFamily = "zq3",
            s1Pattern = EnginePattern.MERLIN9,
            s2Pattern = EnginePattern.MERLIN_VAC
        ),

        VehicleSpec(
            id = "sr75",
            family = "sr75",
            tokens = listOf(
                "hyimpulse",
                "sr75",
                "sr-75",
                "sr 75",
                "hyimpulse sr75"
            ),
            s1Engines = 1, // single HyPLOX-75 hybrid
            s2Engines = 0, // single-stage
            recoverable = true, // parachute recovery Soft-PASS published
            methalox = false,
            fuelName = "Paraffin",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "HyPLOX-75",
            s1Thrust = "~75 kN SL",
            s2Thrust = "—",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "—",
            nerdNote = "HyImpulse SR75: single-stage suborbital hybrid sounding rocket / SL1 tech demonstrator. Published ~11–14 m length (art 12.5 m class), Ø0.64 m, one HyPLOX-75 paraffin+LOX ~75 kN SL, payload ~200–250 kg to ~200–250 km (mission-dependent). Two-stage parachute recovery Soft-PASS. Maiden 2024-05-03 Koonibba; Flight 2 NET day 2026-10-04 (day-precision — Soft-FAIL invent clock/pad). Published HyImpulse/Southern Launch/NSF-class — no invent. Da Vinci art: vehicle_sr75_* GOLD 2026-09-23 (SS×6 white composite hull, LOX cyan + paraffin amber/cream fills, single nozzle).",
            verified = true,
            drawFamily = "sr75",
            s1Pattern = EnginePattern.VACUUM1,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "HyPLOX-75 hybrid",
            s2Name = "—",
            s2EngineName = "—"
        ),

        VehicleSpec(
            id = "nuri",
            family = "nuri",
            tokens = listOf(
                "nuri",
                "kslv-2",
                "kslv2",
                "kslv-ii",
                "kslv ii",
                "kari",
                "누리호",
                "korea space launch vehicle"
            ),
            s1Engines = 4, // 4× KRE-075
            s2Engines = 1, // 1× KRE-075V (S3 KRE-007V Soft-PASS in nerdNote / ship)
            recoverable = false,
            methalox = false, // Jet-A1 + LOX all stages
            fuelName = "RP",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "KRE-075 / KRE-075V / KRE-007V",
            s1Thrust = "~2942 kN SL (4×KRE-075)",
            s2Thrust = "1x KRE-075V VAC",
            ispVac = "—",
            mixRatio = "—",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~200 t GLOW class",
            nerdNote = "Nuri / KSLV-II (KARI): 47.2 m, S1 Ø3.5 m, upper Ø2.6 m, ~200 t GLOW. 3-stage kerolox Jet-A1+LOX — Soft-FAIL invent methane. S1 4×KRE-075 (~300 tf / ~2942 kN SL); S2 1×KRE-075V (~788 kN vac); S3 1×KRE-007V (~69 kN vac). Fairing ~Ø3.3 m (NSF). ~1.5–1.9 t SSO / ~3.3 t LEO class. No SRBs / not recoverable. Maiden 2021-10-21 Naro LP-2; orbital successes 2022-06-21, 2023-05-25, 2025-11-26. Published KARI/NSF/Everyday Astronaut/DongA/EUCASS — Soft-FAIL invent unpublished fairing height. Da Vinci art: vehicle_nuri_* GOLD 2026-09-23 (SS×6 white hull, 3-stage kerolox fills, no SRBs).",
            verified = true,
            drawFamily = "nuri",
            s1Pattern = EnginePattern.CHAMBER4,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "1st (4×KRE-075)",
            s2Name = "2nd (KRE-075V)",
            s2EngineName = "KRE-075V"
        ),

        VehicleSpec(
            id = "h3",
            family = "h3",
            tokens = listOf(
                "h3",
                "h-3",
                "h3-24",
                "h3-24l",
                "h3 24",
                "h3 24l",
                "mmx",
                "martian moons",
                "martian moons exploration"
            ),
            s1Engines = 2,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "LH2",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "LE-9 / LE-5B-3 + SRB-3",
            s1Thrust = "2.9 MN + SRB",
            s2Thrust = "137 kN VAC",
            ispVac = "448 s",
            mixRatio = "5.9 O/F",
            chamberBar = "—",
            s1Dry = "—",
            s1Prop = "~575 t GLOW class (H3-24L)",
            nerdNote = "H3 / H3-24L (JAXA/MHI): ~63 m long-fairing class, Ø5.2 m core, ~575 t GLOW (no payload). S1 2×LE-9 hydrolox; S2 1×LE-5B-3 hydrolox; 4×SRB-3 Ø2.5 m solid. Long fairing ~16.4 m × Ø5.2 m. Tanegashima. MMX / Martian Moons Exploration Soft-PASS token cover. Published JAXA/MHI/MMX press kit — Soft-FAIL invent unpublished. Da Vinci art: vehicle_h3_* GOLD 2026-09-23 (SS×6 white hull, orange SRB-3, hydrolox fills). Solids have no liquid bells on the ENG plate.",
            verified = true,
            drawFamily = "h3",
            s1Pattern = EnginePattern.LE9_2,
            s2Pattern = EnginePattern.RL10,
            s1Name = "1st (2×LE-9+SRB-3)",
            s2Name = "2nd (LE-5B-3)",
            s2EngineName = "LE-5B-3"
        ),

        VehicleSpec(
            id = "atlas",
            family = "atlas",
            tokens = listOf("atlas v", "atlas-v", "atlas 5"),
            s1Engines = 2,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "RD-180 / RL10",
            s1Thrust = "3.8 MN SL",
            s2Thrust = "99 kN VAC",
            ispVac = "450 s",
            mixRatio = "2.72 O/F",
            chamberBar = "257 BAR",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Atlas V. RD-180 is two chambers. SRBs are not liquid bells.",
            verified = true,
            drawFamily = "atlas",
            s1Pattern = EnginePattern.RD180_2,
            s2Pattern = EnginePattern.VACUUM1
        ),
        VehicleSpec(
            id = "firefly",
            family = "firefly",
            tokens = listOf("firefly alpha", "firefly"),
            s1Engines = 4,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "REAVER / LIGHTNING",
            s1Thrust = "736 kN SL",
            s2Thrust = "70 kN VAC",
            ispVac = "322 s",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Firefly Alpha. Four Reaver in a 2x2, one Lightning vacuum.",
            verified = true,
            drawFamily = "firefly",
            s1Pattern = EnginePattern.REAVER4,
            s2Pattern = EnginePattern.VACUUM1
        ),

        VehicleSpec(
            id = "kinetica1",
            family = "kinetica1",
            tokens = listOf(
                "kinetica-1",
                "kinetica 1",
                "kinetica1",
                "kinetica",
                "lijian-1",
                "lijian1",
                "lijian 1",
                "cas space",
                "cas-space",
                "zk-1",
                "zk1"
            ),
            s1Engines = 1,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "SOLID",
            oxName = "SOLID",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "HTPB/APCP stages",
            s1Thrust = "-",
            s2Thrust = "-",
            ispVac = "-",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "CAS Space Kinetica-1 (Lijian-1): all-solid 4-stage HTPB/APCP. Stamp 125 art vehicle_kinetica1_* grain ochre (ox empty). No propane pills. Unpublished fields Unknown.",
            verified = true,
            drawFamily = "kinetica1",
            s1Pattern = EnginePattern.UNKNOWN,
            s2Pattern = EnginePattern.UNKNOWN,
            s1Name = "S1 SOLID",
            s2Name = "S2-S4 UPPER",
            s2EngineName = "SOLID"
        ),

        VehicleSpec(
            id = "pallas1",
            family = "pallas1",
            tokens = listOf(
                "pallas-1",
                "pallas 1",
                "pallas1",
                "galactic energy",
                "galacticenergy"
            ),
            s1Engines = 7,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "RP-1",
            oxName = "LOX",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "Welkin",
            s1Thrust = "7x Welkin SL class",
            s2Thrust = "Welkin Vac",
            ispVac = "-",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Galactic Energy Pallas-1: kerolox paper-doll. Stamp 120 art vehicle_pallas1_*. No propane pills. Unpublished fields Unknown.",
            verified = true,
            drawFamily = "pallas1",
            s1Pattern = EnginePattern.UNKNOWN,
            s2Pattern = EnginePattern.VACUUM1,
            s1Name = "1st (Welkin)",
            s2Name = "2nd (Welkin Vac)",
            s2EngineName = "Welkin Vac"
        ),

        VehicleSpec(
            id = "gravity1",
            family = "gravity1",
            tokens = listOf("gravity-1", "gravity 1", "orienspace"),
            s1Engines = 5,
            s2Engines = 1,
            recoverable = false,
            methalox = false,
            fuelName = "SOLID",
            oxName = "SOLID",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "M1 / M2 / M3",
            s1Thrust = "~600 t-class EST",
            s2Thrust = "-",
            ispVac = "-",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Orienspace Gravity-1. All-solid: 4x M1 strap-ons + M1 vac core + M2 + M3. Barge sea launch (Yellow/East China Sea). ~6.5 t LEO / ~4.2 t SSO; ~42 m / ~3.35 m class. Maiden 2024-01-11 Yunyao sats. Stamp 119: art vehicle_gravity1_* all-solid HTPB ochre (ox empty). Unpublished fields left Unknown.",
            verified = true,
            drawFamily = "gravity1",
            s1Pattern = EnginePattern.UNKNOWN,
            s2Pattern = EnginePattern.UNKNOWN,
            s1Name = "GRAVITY-1 CORE + STRAPONS",
            s2Name = "UPPER (M2/M3)",
            s2EngineName = "M2 / M3"
        ),
        VehicleSpec(
            id = "proton",

            family = "proton",
            tokens = listOf("proton"),
            s1Engines = 6,
            s2Engines = 4,
            recoverable = false,
            methalox = false,
            fuelName = "UDMH",
            boostbackLit = 0,
            landingLit = 0,
            engineName = "RD-275 / RD-0210",
            s1Thrust = "10 MN SL",
            s2Thrust = "2.4 MN VAC",
            ispVac = "327 s",
            mixRatio = "-",
            chamberBar = "-",
            s1Dry = "-",
            s1Prop = "-",
            nerdNote = "Proton-M. Six RD-275 around the core. Stage 2 is four RD-0210.",
            verified = true,
            drawFamily = "proton",
            s1Pattern = EnginePattern.PROTON6,
            s2Pattern = EnginePattern.CHAMBER4
        )
    )

    fun blob(launch: LaunchSnapshot?): String =
        "${launch?.rocketName.orEmpty()} ${launch?.name.orEmpty()} ${launch?.missionName.orEmpty()} ${launch?.provider.orEmpty()}".lowercase()

    fun spec(launch: LaunchSnapshot?): VehicleSpec {
        val n = blob(launch)
        if (n.isBlank()) return GENERIC
        return all.firstOrNull { s -> s.tokens.any { it in n } } ?: GENERIC
    }

    fun family(launch: LaunchSnapshot?): String = spec(launch).family

    fun drawFamily(launch: LaunchSnapshot?): String = spec(launch).drawFamily

    fun isVerified(launch: LaunchSnapshot?): Boolean = spec(launch).verified

    fun needsUpdate(launch: LaunchSnapshot?): Boolean = !isVerified(launch)

    /** Darren LM-8A stack silhouette base name under res/drawable (png/webp). */
    const val CZ8A_DRAWABLE = "vehicle_cz8a"
    const val CZ6A_DRAWABLE = "vehicle_cz6a"
    const val SR75_DRAWABLE = "vehicle_sr75"
    const val NURI_DRAWABLE = "vehicle_nuri"
    const val CZ12_DRAWABLE = "vehicle_cz12"
    const val ZQ3_DRAWABLE = "vehicle_zq3"
    const val GRAVITY1_DRAWABLE = "vehicle_gravity1"
    const val KINETICA1_DRAWABLE = "vehicle_kinetica1"
    const val PALLAS1_DRAWABLE = "vehicle_pallas1"
    const val ELECTRON_DRAWABLE = "vehicle_electron"
    const val KZ11_DRAWABLE = "vehicle_kz11"
    const val CZ2D_DRAWABLE = "vehicle_cz2d"

    const val UPDATE_HEAD = "NEW VEHICLE · DATA UPDATE REQUIRED"
    const val UPDATE_BODY = "This rocket is not in the vehicle book yet. Drawing and numbers ship in a later update. We will not invent them."

    fun engines(launch: LaunchSnapshot?, stage: Int): Int {
        val s = spec(launch)
        return if (stage >= 2) s.s2Engines else s.s1Engines
    }

    fun enginePattern(launch: LaunchSnapshot?, stage: Int): EnginePattern {
        val s = spec(launch)
        if (!s.verified) return EnginePattern.UNKNOWN
        return if (stage >= 2) s.s2Pattern else s.s1Pattern
    }

    fun landingLitFor(launch: LaunchSnapshot?): Int {
        val s = spec(launch)
        return if (MissionFacts.isFlight13(launch)) 10 else s.landingLit
    }

    /** Verified recoverable. GENERIC (verified=false) is unknown, not expended. */
    fun isKnownRecoverable(launch: LaunchSnapshot?): Boolean {
        val s = spec(launch)
        return s.verified && s.recoverable
    }

    /** Verified expendable. recoverable=false + verified=false is unknown. */
    fun isKnownExpendable(launch: LaunchSnapshot?): Boolean {
        val s = spec(launch)
        return s.verified && !s.recoverable
    }

    const val UNKNOWN_RECOVERY = "UNKNOWN · DATA UPDATE REQUIRED"
}
